### ISSUE TITLE
admin.php is deprecated

### ISSUE THREAD

**Issue by fiwswe** [Rainbow-Spike/userhistory#1]
…/data/log/deprecated/*.log shows entries such as this:
`2022-09-06 14:03:59		admin.php is deprecated. It was called from require_once() in /dokuwiki-test/lib/plugins/admin.php:3 Do not require() files yourself. Autoloading should be used instead!`

A grep over the plugins folder turned up this which I suspect is one of the causes of the message:
`/var/www/dokuwiki-test/lib/plugins/userhistory/admin.php:require_once ( DOKU_PLUGIN.'admin.php' );`
See: https://github.com/Comicslate/userhistory/blob/main/admin.php#L5

Commenting the line seems to solve the issue.

fiwswe

**Comment by j0hannes** [comment]
Wouldn't it be sufficient to replace
`require_once ( DOKU_PLUGIN.'admin.php' );`
by
```
spl_autoload_register(function () {
    require_once ( DOKU_PLUGIN.'admin.php' );
});
```

**Comment by fiwswe** [comment]
@j0hannes: I have never used [spl_autoload_register](https://www.php.net/manual/en/function.spl-autoload-register.php) but reading the docs it sounds like it is intended for classes not include files? Though the docs are somewhat unclear to me.

Also `DOKU_PLUGIN.'admin.php'` actually exists but contains code to log the deprecation warning. So how would [spl_autoload_register](https://www.php.net/manual/en/function.spl-autoload-register.php) prevent the require_once from executing?

Possibly if we figure out which version of DW deprecated this (-> [commit history](https://github.com/splitbrain/dokuwiki/commit/e1d9dcc8b460b6f029ac9c8d5d3b8d23b6e73402) of the [/lib/plugins/action.php](https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/action.php) file, which would make Hogfather the first version where this was deprecated) we could use something like:
```
global $updateVersion;

// Note: This is PSEUDO CODE!
// We'd need to implement a string compare function that knows how to compare version numbers.
// Or maybe DW already has a mechanism for checking versions/API versions?
// Also '51.0' is just a guess for the first version of Hogfather.
if ($updateVersion < '51.0') {
    require_once ( DOKU_PLUGIN.'admin.php' );
}
```

But frankly, does anyone really want to support DW versions older than Hogfather? If not then just fix the minor error and when the next DW release comes along and [/lib/plugins/action.php](https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/action.php) is removed, we wouldn't fall on our face.

**Comment by j0hannes** [comment]
I see. Doesn't that mean you could simply delete the require_once statement assuming that nobody would install the plugin for a DW version that is deprecated?

**Comment by fiwswe** [comment]
Commenting as mentioned or deleting the line will both work, yes.

**Comment by Klap-in** [comment]
Multiple versions of DokuWiki have already auto loading in place, so the require can be deleted safely.
Also the defines at the start of that file are not needed anymore.

Btw, for guidance for updates of deprecated code, I try to collect here examples with suggestions how to do improvements/replacements. https://www.dokuwiki.org/devel:releases:refactor2020
