### ISSUE TITLE
Compatibility with release "Igor"?

### ISSUE THREAD

**Issue by j0hannes** [Rainbow-Spike/userhistory#2]
Hi,

Is this plugin compatible with the latest Dokuwiki release?

**Comment by fiwswe** [comment]
So far a test Wiki running DW 2022-07-31a "Igor", PHP 8.0.23, [User History Plugin](https://www.dokuwiki.org/plugin%3Auserhistory) 2021-02-07 seems to work fine.

One minor issue is #1.

HTH
fiwswe

**Comment by Rainbow-Spike** [comment]
this issue was merged now. have a good day.
