### ISSUE TITLE
Extremely long operation times, timeouts

### ISSUE THREAD

**Issue by fiwswe** [Rainbow-Spike/userhistory#5]
DokuWiki 2024-02-06b "Kaos"
[User History Plugin](https://www.dokuwiki.org/plugin%3Auserhistory) 2021-02-07
[sprintDoc Template](https://www.dokuwiki.org/template%3Asprintdoc) 2024-03-30
PHP 8.3.10 (FPM)
OpenBSD 7.5

On a somewhat large Wiki (≈300 MB, mostly text not much media content), which is several years old with lots of changes, clicking on a the link for a user takes extremely long and in some cases yields empty content (the template header, sidebar, etc are shown, but no page content. With my template the content are is simply the background grey.

I suspect the operations done by the plugin time out. This is confirmed by the Apache httpd error log:
`[Mon Aug 05 18:39:38.435108 2024] [proxy_fcgi:error] [pid 28842:tid 15230400955968] (70007)The timeout specified has expired: [client 2003:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:63345] AH01075: Error dispatching request to : (polling), referer: https://hostname/doku.php?id=start&do=admin&page=userhistory` (anonymised)

**Comment by fiwswe** [comment]
Possibly #6 contributes to the long operations times due to the deprecation logging?

**Comment by Rainbow-Spike** [comment]
Now #6 merged. Please update this plugin to your site and test it again

**Comment by fiwswe** [comment]
Seems to be fixed. Thx!
